# Generated by Django 2.0.5 on 2018-05-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='quesion',
            new_name='question',
        ),
    ]
